export const STATUS_COLORS: Record<string, string> = {
  PENDING: 'gray',
  PENDING_VALIDATION: 'gray',
  VALIDATING: 'blue',
  PROCESSING: 'blue',
  VALIDATED: 'green',
  COMPLETED: 'green',
  VALIDATED_WITH_ERRORS: 'orange',
  PARTIALLY_FAILED: 'orange',
  FAILED: 'red',
  VALIDATION_FAILED: 'red',
  CANCELLED: 'gray',
  APPLYING: 'blue',
  APPLIED: 'green',
  REGISTERED: 'green',
  UPDATED: 'green',
  SENT: 'blue',
  WAITING_PROVIDER_EVENT: 'blue',
  REMOVING: 'orange',
  REMOVED: 'gray',
  IN_AGREEMENT: 'purple',
  AGREEMENT_BREACHED: 'red',
  PAID: 'teal',
  ACTIVE: 'green',
  INACTIVE: 'gray',
  SUSPENDED: 'orange',
};
