import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Box, Button, Card, Flex, HStack, Input, NativeSelect, Stack, Text, Textarea } from '@chakra-ui/react';
import { LuPlus, LuTrash2, LuCopy, LuSave } from 'react-icons/lu';
import api from '@/lib/api';
import { toaster } from '@/components/ui/toaster';

type Channel = 'SMS' | 'EMAIL' | 'AI_VOICE_CALL';
type Template = { id: string; name: string; channel: Channel; content: string; isDefault: boolean };
type Rule = { id: string; name: string; active: boolean; schedule: { frequency: 'DAILY' | 'WEEKLY'; time: string; days?: number[] }; conditions: Array<{ field: string; operator: string; value: string | number }>; channel: Channel; templateId: string; template: Template };
const channelNames: Record<Channel, string> = { SMS: 'SMS', EMAIL: 'E-mail', AI_VOICE_CALL: 'Ligação com IA' };
const blankCondition = { field: 'paymentStatus', operator: 'eq', value: 'OPEN' };

function AgentSettingsPanel({ walletId, canEdit }: { walletId: string; canEdit: boolean }) {
  const [agent, setAgent] = useState({ name: '', prompt: '', greetings: '', modelVersion: 'lumen-1', voiceId: '', active: true });
  const [loading, setLoading] = useState(false);
  useEffect(() => { api.get(`/wallets/${walletId}/liguelead-agent`).then(({ data }) => { if (data) setAgent({ name: data.name ?? '', prompt: data.prompt ?? '', greetings: data.greetings ?? '', modelVersion: data.modelVersion ?? 'lumen-1', voiceId: data.voiceId ?? '', active: data.active ?? true }); }).catch(() => undefined); }, [walletId]);
  const save = async () => { setLoading(true); try { await api.put(`/wallets/${walletId}/liguelead-agent`, agent); toaster.create({ title: 'Configuração do agente salva', type: 'success' }); } catch { toaster.create({ title: 'Não foi possível salvar o agente', type: 'error' }); } finally { setLoading(false); } };
  return <Card.Root><Card.Header><Card.Title>Agente de ligação com IA</Card.Title><Text fontSize="sm" color="fg.muted">Configuração do agente LigueLead existente para esta carteira.</Text></Card.Header><Card.Body><Stack gap="3"><Input value={agent.name} onChange={(e) => setAgent({ ...agent, name: e.target.value })} placeholder="Nome do agente" aria-label="Nome do agente" /><Textarea value={agent.prompt} onChange={(e) => setAgent({ ...agent, prompt: e.target.value })} placeholder="Prompt do agente" aria-label="Prompt do agente" minH="130px" /><Textarea value={agent.greetings} onChange={(e) => setAgent({ ...agent, greetings: e.target.value })} placeholder="Saudação inicial" aria-label="Saudação inicial" /><Button alignSelf="start" colorPalette="blue" disabled={!canEdit || !agent.name.trim() || !agent.prompt.trim()} loading={loading} onClick={() => void save()}><LuSave /> Salvar agente</Button></Stack></Card.Body></Card.Root>;
}

export function CommunicationRulesPanel({ walletId, canEdit, initialSection = 'rules' }: { walletId: string; canEdit: boolean; initialSection?: 'rules' | 'channels' }) {
  const qc = useQueryClient();
  const [section, setSection] = useState<'rules' | 'channels'>(initialSection);
  const [selectedRule, setSelectedRule] = useState<string | null>(null);
  const [ruleName, setRuleName] = useState('');
  const [frequency, setFrequency] = useState<'DAILY' | 'WEEKLY'>('DAILY');
  const [time, setTime] = useState('07:00');
  const [conditions, setConditions] = useState<Array<{ field: string; operator: string; value: string | number }>>([{ ...blankCondition }]);
  const [channel, setChannel] = useState<Channel>('SMS');
  const [templateId, setTemplateId] = useState('');
  const [templateName, setTemplateName] = useState('');
  const [templateContent, setTemplateContent] = useState('');
  const [templateChannel, setTemplateChannel] = useState<Channel>('SMS');

  const templatesQuery = useQuery({ queryKey: ['communication-templates', walletId], queryFn: async () => (await api.get<Template[]>(`/wallets/${walletId}/communication/templates`)).data });
  const rulesQuery = useQuery({ queryKey: ['communication-rules', walletId], queryFn: async () => (await api.get<Rule[]>(`/wallets/${walletId}/communication/rules`)).data });
  const templates = templatesQuery.data ?? [];
  const rules = rulesQuery.data ?? [];
  const availableTemplates = useMemo(() => templates.filter((item) => item.channel === channel), [templates, channel]);

  const refresh = () => Promise.all([qc.invalidateQueries({ queryKey: ['communication-templates', walletId] }), qc.invalidateQueries({ queryKey: ['communication-rules', walletId] })]);
  const createRule = useMutation({ mutationFn: async () => api.post(`/wallets/${walletId}/communication/rules`, { name: ruleName, schedule: { frequency, time }, conditions, channel, templateId }), onSuccess: () => { void refresh(); setSelectedRule(null); setRuleName(''); toaster.create({ title: 'Regra criada', type: 'success' }); }, onError: () => toaster.create({ title: 'Não foi possível criar a regra', type: 'error' }) });
  const toggleRule = useMutation({ mutationFn: async (rule: Rule) => api.patch(`/wallets/${walletId}/communication/rules/${rule.id}`, { active: !rule.active }), onSuccess: () => void refresh() });
  const deleteRule = useMutation({ mutationFn: async (rule: Rule) => api.delete(`/wallets/${walletId}/communication/rules/${rule.id}`), onSuccess: () => void refresh() });
  const createTemplate = useMutation({ mutationFn: async () => api.post(`/wallets/${walletId}/communication/templates`, { channel: templateChannel, name: templateName, content: templateContent }), onSuccess: () => { void refresh(); setTemplateName(''); setTemplateContent(''); toaster.create({ title: 'Template criado', type: 'success' }); }, onError: () => toaster.create({ title: 'Não foi possível criar o template', type: 'error' }) });
  const exportTemplate = useMutation({ mutationFn: async (template: Template) => api.post(`/wallets/${walletId}/communication/templates/${template.id}/export-default`), onSuccess: () => { void refresh(); toaster.create({ title: 'Template exportado como padrão da conta', type: 'success' }); }, onError: () => toaster.create({ title: 'Não foi possível exportar o template', type: 'error' }) });

  function newRule() {
    setRuleName('Nova regra de comunicação'); setFrequency('DAILY'); setTime('07:00'); setConditions([{ ...blankCondition }]); setChannel('SMS'); setTemplateId(''); setSelectedRule('new');
  }
  function pickRule(rule: Rule) {
    setSelectedRule(rule.id); setRuleName(rule.name); setFrequency(rule.schedule.frequency); setTime(rule.schedule.time); setConditions(rule.conditions); setChannel(rule.channel); setTemplateId(rule.templateId);
  }

  return <Stack gap="5">
    <HStack borderBottomWidth="1px" gap="1" role="tablist" aria-label="Configuração de comunicação">
      <Button variant={section === 'rules' ? 'subtle' : 'ghost'} role="tab" aria-selected={section === 'rules'} onClick={() => setSection('rules')}>Regras de comunicação</Button>
      <Button variant={section === 'channels' ? 'subtle' : 'ghost'} role="tab" aria-selected={section === 'channels'} onClick={() => setSection('channels')}>Canais e templates</Button>
    </HStack>
    {section === 'rules' ? <Flex gap="5" align="start" direction={{ base: 'column', lg: 'row' }}>
      <Card.Root width={{ base: '100%', lg: '280px' }} flexShrink="0"><Card.Header><Flex justify="space-between" align="center"><Card.Title>Fluxos</Card.Title>{canEdit && <Button size="sm" aria-label="Criar regra" onClick={newRule}><LuPlus /></Button>}</Flex></Card.Header><Card.Body pt="0"><Stack gap="2">{rules.map((rule) => <HStack key={rule.id}><Button flex="1" justifyContent="start" variant={selectedRule === rule.id ? 'subtle' : 'ghost'} onClick={() => pickRule(rule)}>{rule.name}</Button><Text fontSize="xs" color={rule.active ? 'green.600' : 'fg.muted'}>{rule.active ? 'Ativa' : 'Pausada'}</Text></HStack>)}{rules.length === 0 && <Text color="fg.muted" fontSize="sm">Nenhuma regra criada.</Text>}</Stack></Card.Body></Card.Root>
      <Box flex="1" minW="0">{selectedRule === 'new' ? <Card.Root><Card.Header><Card.Title>Criar fluxo de comunicação</Card.Title></Card.Header><Card.Body><Stack gap="4">
        <Input value={ruleName} onChange={(e) => setRuleName(e.target.value)} aria-label="Nome da regra" placeholder="Nome da regra" />
        <Box><Text fontWeight="semibold" mb="2">Quando</Text><HStack><NativeSelect.Root><NativeSelect.Field value={frequency} onChange={(e) => setFrequency(e.target.value as 'DAILY' | 'WEEKLY')}><option value="DAILY">Todos os dias</option><option value="WEEKLY">Toda semana</option></NativeSelect.Field><NativeSelect.Indicator /></NativeSelect.Root><Input type="time" value={time} onChange={(e) => setTime(e.target.value)} aria-label="Horário de envio" /></HStack></Box>
        <Box><Flex justify="space-between" align="center" mb="2"><Text fontWeight="semibold">Se (todas as condições devem corresponder)</Text><Button size="xs" variant="outline" onClick={() => setConditions((items) => [...items, { ...blankCondition }])}><LuPlus /> Condição</Button></Flex><Stack>{conditions.map((condition, index) => <HStack key={index} align="start"><NativeSelect.Root><NativeSelect.Field value={condition.field} onChange={(e) => setConditions((items) => items.map((item, i) => i === index ? { ...item, field: e.target.value, operator: e.target.value === 'paymentStatus' ? 'eq' : item.operator, value: e.target.value === 'paymentStatus' ? 'OPEN' : '' } : item))}><option value="paymentStatus">Status financeiro</option><option value="offerValue">Valor da oferta (R$)</option><option value="agingDays">Tempo de dívida (dias)</option></NativeSelect.Field><NativeSelect.Indicator /></NativeSelect.Root>{condition.field === 'paymentStatus' ? <NativeSelect.Root><NativeSelect.Field value={String(condition.value)} onChange={(e) => setConditions((items) => items.map((item, i) => i === index ? { ...item, value: e.target.value } : item))}><option value="OPEN">Em aberto</option><option value="IN_AGREEMENT">Em acordo</option><option value="INSTALLMENT">Parcelado</option><option value="AGREEMENT_BREACHED">Acordo quebrado</option><option value="PAID">Pago</option></NativeSelect.Field><NativeSelect.Indicator /></NativeSelect.Root> : <><NativeSelect.Root width="130px"><NativeSelect.Field value={condition.operator} onChange={(e) => setConditions((items) => items.map((item, i) => i === index ? { ...item, operator: e.target.value } : item))}><option value="eq">Igual a</option><option value="gt">Maior que</option><option value="lt">Menor que</option></NativeSelect.Field><NativeSelect.Indicator /></NativeSelect.Root><Input type="number" min="0" value={String(condition.value)} onChange={(e) => setConditions((items) => items.map((item, i) => i === index ? { ...item, value: Number(e.target.value) } : item))} /></>}{conditions.length > 1 && <Button size="sm" variant="ghost" colorPalette="red" aria-label="Remover condição" onClick={() => setConditions((items) => items.filter((_, i) => i !== index))}><LuTrash2 /></Button>}</HStack>)}</Stack></Box>
        <Box><Text fontWeight="semibold" mb="2">Então</Text><HStack><NativeSelect.Root><NativeSelect.Field value={channel} onChange={(e) => { setChannel(e.target.value as Channel); setTemplateId(''); }}><option value="SMS">SMS</option><option value="EMAIL">E-mail</option><option value="AI_VOICE_CALL">Ligação com IA</option></NativeSelect.Field><NativeSelect.Indicator /></NativeSelect.Root><NativeSelect.Root><NativeSelect.Field value={templateId} onChange={(e) => setTemplateId(e.target.value)}><option value="">Escolha um template</option>{availableTemplates.map((template) => <option key={template.id} value={template.id}>{template.name}{template.isDefault ? ' (padrão)' : ''}</option>)}</NativeSelect.Field><NativeSelect.Indicator /></NativeSelect.Root></HStack>{availableTemplates.length === 0 && <Text mt="2" fontSize="sm" color="fg.muted">Crie um template na aba Canais e templates para este canal.</Text>}</Box>
        <Button colorPalette="blue" disabled={!canEdit || !ruleName.trim() || !templateId || createRule.isPending} loading={createRule.isPending} onClick={() => createRule.mutate()}><LuSave /> Salvar regra</Button>
      </Stack></Card.Body></Card.Root> : selectedRule ? <Card.Root><Card.Header><Card.Title>{rules.find((rule) => rule.id === selectedRule)?.name ?? ruleName}</Card.Title></Card.Header><Card.Body><Stack gap="4"><Text>Agenda: {rules.find((rule) => rule.id === selectedRule)?.schedule.frequency === 'DAILY' ? 'Todos os dias' : 'Toda semana'} às {rules.find((rule) => rule.id === selectedRule)?.schedule.time}</Text><Text>Condições: {rules.find((rule) => rule.id === selectedRule)?.conditions.map((c) => `${c.field} ${c.operator} ${c.value}`).join(' e ')}</Text><Text>Ação: {channelNames[rules.find((rule) => rule.id === selectedRule)!.channel]} usando “{rules.find((rule) => rule.id === selectedRule)?.template.name}”</Text><HStack><Button variant="outline" disabled={!canEdit} onClick={() => toggleRule.mutate(rules.find((rule) => rule.id === selectedRule)!)}>{rules.find((rule) => rule.id === selectedRule)?.active ? 'Pausar regra' : 'Ativar regra'}</Button><Button colorPalette="red" variant="outline" disabled={!canEdit} onClick={() => { deleteRule.mutate(rules.find((rule) => rule.id === selectedRule)!); setSelectedRule(null); }}><LuTrash2 /> Excluir</Button></HStack></Stack></Card.Body></Card.Root> : <Text color="fg.muted">Selecione uma regra ou use + para criar um fluxo.</Text>}</Box>
    </Flex> : <Stack gap="5"><AgentSettingsPanel walletId={walletId} canEdit={canEdit} /><Card.Root><Card.Header><Card.Title>Canais</Card.Title><Text fontSize="sm" color="fg.muted">Cadastre vários modelos por canal. As regras selecionam o template a utilizar.</Text></Card.Header><Card.Body><Stack gap="4"><HStack><NativeSelect.Root><NativeSelect.Field value={templateChannel} onChange={(e) => setTemplateChannel(e.target.value as Channel)}><option value="SMS">SMS</option><option value="EMAIL">E-mail</option><option value="AI_VOICE_CALL">Ligação com IA</option></NativeSelect.Field><NativeSelect.Indicator /></NativeSelect.Root><Input value={templateName} onChange={(e) => setTemplateName(e.target.value)} placeholder="Nome do template" aria-label="Nome do template" /></HStack><Textarea value={templateContent} onChange={(e) => setTemplateContent(e.target.value)} minH="140px" placeholder={templateChannel === 'AI_VOICE_CALL' ? 'Prompt/instruções para a ligação com IA' : 'Conteúdo da mensagem; variáveis como {{nome}} podem ser usadas'} aria-label="Conteúdo do template" /><Button alignSelf="start" colorPalette="blue" disabled={!canEdit || !templateName.trim() || !templateContent.trim()} loading={createTemplate.isPending} onClick={() => createTemplate.mutate()}><LuPlus /> Criar template</Button></Stack></Card.Body></Card.Root>
      {(['SMS', 'EMAIL', 'AI_VOICE_CALL'] as Channel[]).map((item) => <Card.Root key={item}><Card.Header><Card.Title>{channelNames[item]}</Card.Title></Card.Header><Card.Body><Stack gap="3">{templates.filter((template) => template.channel === item).map((template) => <HStack key={template.id} borderWidth="1px" rounded="md" p="3" align="start"><Box flex="1"><Text fontWeight="semibold">{template.name} {template.isDefault && <Text as="span" color="blue.600" fontSize="sm">· padrão</Text>}</Text><Text whiteSpace="pre-wrap" fontSize="sm" color="fg.muted" mt="1">{template.content}</Text></Box>{!template.isDefault && <Button size="sm" variant="outline" disabled={!canEdit || exportTemplate.isPending} onClick={() => exportTemplate.mutate(template)} title="Disponibiliza este template como padrão nas outras carteiras"><LuCopy /> Exportar como padrão</Button>}</HStack>)}{templates.filter((template) => template.channel === item).length === 0 && <Text color="fg.muted" fontSize="sm">Nenhum template cadastrado.</Text>}</Stack></Card.Body></Card.Root>)}</Stack>}
  </Stack>;
}

